// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGeT0iOorWU9hsCSfyLxZB0l2dTNF3ajQ',
    appId: '1:345352254523:android:2049e3c890a0411292581e',
    messagingSenderId: '345352254523',
    projectId: 'examenflutter-41e66',
    databaseURL: 'https://examenflutter-41e66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'examenflutter-41e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlCg6HgFk49brmKSG0gqxgjFQrxm6tBI',
    appId: '1:345352254523:ios:496233aca1b378f892581e',
    messagingSenderId: '345352254523',
    projectId: 'examenflutter-41e66',
    databaseURL: 'https://examenflutter-41e66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'examenflutter-41e66.appspot.com',
    iosBundleId: 'com.example.examenPractic',
  );
}
